package com.demo.winwang.tigermachine;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.demo.winwang.tigermachine.User;
import com.demo.winwang.tigermachine.widget.UserCaidan;
import com.demo.winwang.tigermachine.UserOrdi;
import com.demo.winwang.tigermachine.UserShine;

import com.demo.winwang.tigermachine.UserDao;
import com.demo.winwang.tigermachine.UserCaidanDao;
import com.demo.winwang.tigermachine.UserOrdiDao;
import com.demo.winwang.tigermachine.UserShineDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig userCaidanDaoConfig;
    private final DaoConfig userOrdiDaoConfig;
    private final DaoConfig userShineDaoConfig;

    private final UserDao userDao;
    private final UserCaidanDao userCaidanDao;
    private final UserOrdiDao userOrdiDao;
    private final UserShineDao userShineDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userCaidanDaoConfig = daoConfigMap.get(UserCaidanDao.class).clone();
        userCaidanDaoConfig.initIdentityScope(type);

        userOrdiDaoConfig = daoConfigMap.get(UserOrdiDao.class).clone();
        userOrdiDaoConfig.initIdentityScope(type);

        userShineDaoConfig = daoConfigMap.get(UserShineDao.class).clone();
        userShineDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        userCaidanDao = new UserCaidanDao(userCaidanDaoConfig, this);
        userOrdiDao = new UserOrdiDao(userOrdiDaoConfig, this);
        userShineDao = new UserShineDao(userShineDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(UserCaidan.class, userCaidanDao);
        registerDao(UserOrdi.class, userOrdiDao);
        registerDao(UserShine.class, userShineDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        userCaidanDaoConfig.clearIdentityScope();
        userOrdiDaoConfig.clearIdentityScope();
        userShineDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserCaidanDao getUserCaidanDao() {
        return userCaidanDao;
    }

    public UserOrdiDao getUserOrdiDao() {
        return userOrdiDao;
    }

    public UserShineDao getUserShineDao() {
        return userShineDao;
    }

}
